pipeline:
  name: go-ci-pipeline
  identifier: gocipipeline
  projectIdentifier: default_project
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: build test and run
        identifier: build_test_and_run
        description: Run Unit Tests, Build, and Push to Docker
        template:
          templateRef: gopipeline
          versionLabel: v1
          templateInputs:
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: run_unit_test
                      type: Run
                      spec:
                        connectorRef: <+input>.allowedValues(account.harnessImage)
                  - step:
                      identifier: go_build
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: Build_And_Push_Docker_Registry
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
                        repo: <+input>
