pipeline:
  name: go-ci-pipeline
  identifier: gocipipeline
  projectIdentifier: default_project
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: build test and run
        identifier: build_test_and_run
        description: Run Unit Tests, Build, and Push to Docker
        template:
          templateRef: gopipeline
          versionLabel: v1
          templateInputs:
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: run_unit_test
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: go_build
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: Build_And_Push_Docker_Registry
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: docker
                        repo: mkandylis/go-image-har
    - stage:
        name: deploy-go
        identifier: deploygo
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: harnessguestbookdep
          environment:
            environmentRef: harnessdevenvdep
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradep
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
